-- LOR1-2: Replace Supabase auth with Microsoft Entra External ID
--
-- The users.id column was originally declared as:
--   id uuid primary key references auth.users(id) on delete cascade
--
-- With Entra External ID the user identifier is the OID (Object ID) claim
-- from the Microsoft identity platform JWT. OIDs are standard UUIDs (RFC 4122
-- version 4), so the uuid type is fully compatible — no type change is needed.
--
-- What DOES change is the foreign-key constraint: we no longer want a hard
-- reference to auth.users because Supabase Auth is no longer used for
-- authentication. We drop that constraint and let the backend (which validates
-- the Entra JWT and upserts user rows) manage referential integrity.
--
-- IMPORTANT: run this migration AFTER you have stopped using Supabase Auth
-- sign-ins and BEFORE you start inserting rows with Entra OIDs. If existing
-- rows already have Supabase auth UUIDs you will need a data migration to map
-- them to the corresponding Entra OIDs first.

-- 1. Drop the FK to auth.users so Entra OIDs can be stored freely.
alter table users drop constraint if exists users_id_fkey;

-- 2. Add a comment documenting the new semantics.
comment on column users.id is
  'Microsoft Entra External ID Object ID (OID claim). UUID format, from a '
  'different namespace than Supabase Auth UIDs. Set by the backend on first '
  'sign-in; never auto-generated by the database.';

-- 3. The RLS policies that reference auth.uid() will no longer match Entra
--    OIDs (auth.uid() returns the Supabase auth UID, not the Entra OID). The
--    backend uses the service-role key which bypasses RLS, so the app will
--    continue to work. We drop the now-stale policies to avoid confusion; the
--    service-role key + explicit org_id scoping in every query is the sole
--    enforcement layer going forward.
drop policy if exists "users can read self" on users;
drop policy if exists "members can read own org" on organisations;
drop policy if exists "org members can read own docs" on documents;
drop policy if exists "org members can insert" on documents;
drop policy if exists "org members can update own docs" on documents;

-- 4. Disable RLS on the tables that were relying on auth.uid()-based policies.
--    The backend enforces org isolation at the query level (see requireAuth
--    middleware), so RLS is not providing additional protection here.
--    Re-enable with Entra-aware policies if you later expose direct Supabase
--    client access from the frontend.
alter table users disable row level security;
alter table organisations disable row level security;
alter table documents disable row level security;
